version: "3.1"


services:
  app:       
    build: 
      dockerfile: ./docker/Dockerfile
      context: ./
    image: conda-template
    env_file:
      - .env
    command: 
      - "echo Hi"
      - "echo Hello"
      - "echo world" 
      - "wait -n"
    volumes:
      - ./src:/opt/app/
  
